[theme]
primaryColor = "#1976D2"  # Royal Blue (for buttons and highlights)
backgroundColor = "#E3F2FD"  # Soft sky blue background
secondaryBackgroundColor = "#90CAF9"  # Light blue sidebar background
textColor = "#0A2540"  # Deep navy blue for strong contrast
font = "sans serif"  # Options: "sans serif", "serif", "monospace"
